config/routes.rb
Tubes::Application.routes.draw do
  root :to => "home#index"
  
  resources :users
  resources :sessions
  resources :categories
  resources :products
  resources :articles
  resources :comments
  
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"  
  
  namespace :admin do
   resources :categories
  end
 

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :id, :title, :body, :user_id
  has_many :comments, :dependent => :destroy
  
    validates :title, :presence => true,
                      :length => {:minimum => 3},
                      :uniqueness => true
    
    validates :body, :presence => true
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :require_login, :only => [:create, :new, :edit, :update, :destroy]
  before_filter :find_article, :only => [:edit, :update, :show, :destroy]
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.create(params[:article])
    if @article.save
      flash[:notice] = "Success save into database"
      redirect_to articles_path
        else
          flash[:notice] = "Failed save into database"
          render :action => :new
        end
  end
  
  def edit
  end
  
  def update
    if @article.update_attributes(params[:article])
      flash[:notice] = "Success update and save into database"
      redirect_to articles_path
        else
          flash[:notice] = "failed to update and save into database"
          render :action => edit
        end
  end

  def index
    @articles = Article.all
  end

  def show
    @user = User.find(@article.user_id)
    @comment = Comment.new
    @comments = Comment.where("article_id = #{params[:id]}")
  end
  
  def destroy
    @article.destroy
    flash[:notice] = "Success delete from database"
    redirect_to articles_path
  end
  
  def find_article
    @article = Article.find(params[:id])
  end
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_comments.html.erb
<h2>Comments</h2>

  <% @comments.each do |com| %>
    Name: <%= @user.name %><br />
    Comment: <%= com.comment %>
  <% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

  <% if @article.errors.any? %>
    <% @article.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
  
  <table>
    <%= form_for(@article) do |a| %>
    <%= a.hidden_field :user_id, :value => @article.user_id %>
      <tr>
        <th>Title</th>
        <td>:</td>
        <td><%= a.text_field :title %></td>
      </tr>
      <tr>
        <th>Body</th>
        <td>:</td>
        <td><%= a.text_area :body %></td>
      </tr>
      <tr>
        <td>
          <%= a.submit %>
          <%= link_to "back", articles_path %>
        </td>
      </tr>
    <% end %>
  </table>

app/views/articles/index.html.erb
<h3>Listing Articles</h3>
  
  <table>
    <% @articles.each do |a| %>
    <tr>
      <th>Title</th>
      <td>:</td>
      <td><%= a.title %></td>
    </tr>
    <tr>
      <th>Body</th>
      <td>:</td>
      <td><%= a.body.truncate(40) %></td>
    </tr>
    <tr>
      <td>Posted at</td>
      <td>:</td>
      <td><%= a.created_at %></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td><%= link_to "See more", article_path(a.id), :method => :get %>
        <% if session[:user_id]%>
          <% if current_user.id == a.user_id || current_user.is_admin? %>
            <%= link_to "Edit", edit_article_path(a.id) %>
            <%= link_to "Delete", article_path(a.id), :method => :delete, :confirm => 'Are You sure to Delete this ?' %>
          <% end %>
        <% end %>
       </td>
    </tr>
    <% end %>
  </table>

app/views/articles/new.html.erb
<h2>New Article</h2>
  
  <% if @article.errors.any? %>
      <% for message in @article.errors.full_messages %>
          <li><%= message %></li>
      <% end %>
  <% end %>
  
  <%= form_for @article do |a|%>
    <table>
      <%= a.hidden_field :user_id, :value => current_user.id %>
      <tr>
        <th>Title</th>
        <td>:</td>
        <td><%= a.text_field :title %></td>
      </tr>
      <tr>
        <th>Body</th>
        <td>:</td>
        <td><%= a.text_area :body %></td>
      </tr>
      <tr>
        <td>
          <%= a.submit %>
          <%= link_to "back", articles_path %>
        </td>
      </tr>
    </table>
  <% end %>

app/views/articles/show.html.erb
<h2>More Information About Article</h2>
  
  <% if @comment.errors.any? %>
      <% for message in @comment.errors.full_messages %>
          <li><%= message %></li>
      <% end %>
  <% end %>
  
  <table>
    <tr>
      <th>Title</th>
      <td>:</td>
      <td><%= @article.title %></td>
    </tr>
    <tr>
      <th>Body</th>
      <td>:</td>
      <td><%= @article.body %></td>
    </tr>
    <tr>
      <th>Writter</th>
      <td>:</td>
      <td><%= @user.name %></td>
    </tr>
  </table>
  
  <div id="comments">
    <%= render :partial => "comments", :locals => {:comments => @comments}  %>
  </div>
  
  <% if current_user %>  
    <h2>Add a comment:</h2>
    <%= form_for @comment, :url => comments_path, :remote => true do |f| %>
      <%= f.hidden_field :article_id, :value => @article.id %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <div class="field">
        <%= f.label :comment %><br />
        <%= f.text_area :comment %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  <% else %>
    <p><strong>
    If you want to comment..?<br />
    you must <%= link_to "Log_in", :root %> first
    </strong></p>
  <% end %>  
  
  <%= link_to "Back", articles_path %>
  <% if session[:user_id]%>
    <% if current_user.id == @article.user_id || current_user.is_admin? %>
      <%= link_to "Edit", edit_article_path(@article.id) %>
    <% end %>
  <% end %>