config/routes.rb
Tubes::Application.routes.draw do
  root :to => "home#index"
  
  resources :users
  resources :sessions
  resources :categories
  resources :products
  resources :articles
  resources :comments
  
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"  
  
  namespace :admin do
   resources :categories
  end
 

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @articles = Article.all
    @products = Product.all
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<hr />
<h2 class="home_h2">Listing Product</h2>
<ul class="list_home">
  <% @products.each do |pro| %>
    <li>
      <table class="list_home_product">
        <tr>
          <th>Name</th>
          <td>:</td>
          <td><%= pro.name %></td>
        </tr>
        <tr>
          <th>Price</th>
          <td>:</td>
          <td><%= pro.price %></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td><%= link_to "See more", product_path(pro.id), :method => :get %>
          <% if session[:user_id]%>
              <% if current_user.id == pro.user_id || current_user.is_admin? %>
                <%= link_to "Edit", edit_product_path(pro.id) %>
                <%= link_to "Delete", product_path(pro.id), :confirm => 'Are You sure to Delete this ?', :method => :delete %>
              <% end %>
          <% end %>
          </td>
        </tr>
      </table>
    </li>
  <% end %>
</ul>
<div class="clear"></div>

<hr/>
<h2 class="home_h2">Listing Article</h2>
<table class="sidearticle">
    <% @articles.each do |a| %>
    <tr>
      <th>Title</th>
      <td>:</td>
      <td><%= a.title %></td>
    </tr>
    <tr>
      <th>Body</th>
      <td>:</td>
      <td><%= a.body.truncate(40) %></td>
    </tr>
    <tr>
      <td>Posted at</td>
      <td>:</td>
      <td><%= a.created_at %></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td><%= link_to "See more", article_path(a.id), :method => :get %>
        <% if session[:user_id]%>
          <% if current_user.id == a.user_id || current_user.is_admin? %>
            <%= link_to "Edit", edit_article_path(a.id) %>
            <%= link_to "Delete", article_path(a.id), :method => :delete, :confirm => 'Are You sure to Delete this ?' %>
          <% end %>
        <% end %>
       </td>
    </tr>
    <% end %>
</table>