config/routes.rb
Tubes::Application.routes.draw do
  root :to => "home#index"
  
  resources :users
  resources :sessions
  resources :categories
  resources :products
  resources :articles
  resources :comments
  
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"  
  
  namespace :admin do
   resources :categories
  end
 

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :product
  
  attr_accessible :id, :name, :parent_id
  
  validates :name, :presence => true,
                   :length => {:minimum => 3},
                   :uniqueness => true
  
  scope :categorychild, lambda { |parent_id| where("parent_id = ?", parent_id) }
  
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_filter :require_admin_login
  before_filter :find, :only => [:show, :edit, :update, :destroy]
  def index
    @categories = Category.all
  end
  
  def show
  end
  
  def new
    @category = Category.new
    @parent_category = Category.where("parent_id IS null").map{|c| [c.name, c.id]}
  end

  def create
    @category = Category.create(params[:category])
    if @category.save
      flash[:notice] = "Success save into database"
      redirect_to admin_categories_path
        else
          flash[:notice] = "Please try Again"
          render :action => :new
        end
  end
  
  def edit
    @parent_category = Category.where("parent_id IS null").map{|c| [c.name, c.id]}
  end
  
  def update
    if @category.update_attributes(params[:category])
      flash[:notice] = "Success Update and save into database"
      redirect_to admin_categories_path
        else
          flash[:notice] = "please try again to update"
          render :action => :edit
        end
  end
  
  def destroy
    @childcategory = Category.categorychild(params[:id])
    @childcategory.each do |cat|
      cat.destroy
    end
    
    @category.destroy
    flash[:notice] = "Success delete data from database"
    redirect_to admin_categories_path
  end
  
  def find
    @category = Category.find(params[:id])
  end
    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    @categories = Category.all
  end
  
  def new
  end

  def create
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
  end
   
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<h2>Edit Form</h2>

  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>

  <%= form_for [:admin,@category] do |cat|%>
    <table>	
      <tr>
        <td><%= cat.label :name %></td>
        <td>:</td>
        <td><%= cat.text_field :name %></td>
      </tr>
      <tr>
        <td><%= cat.label :parent_id %></td>
        <td>:</td>
        <td><%= cat.select :parent_id, @parent_category, { :prompt => true } %></td>
      </tr>
      <tr>
        <td><%= cat.submit %></td>
        <td></td>
        <td><%= link_to "back", admin_categories_path %></td>
      </tr>
    </table>
  <% end %>

app/views/admin/categories/index.html.erb
<h3>Listing Category</h3>
  
  <%= flash[:error] %>
  
  <%= link_to "New Category", new_admin_category_path %><br /><br />
  <table>
    <tr>
      <th>No</th>
      <th>Name</th>
      <th>Parent Category</th>
      <th>Action</th>
    </tr>
    <% @categories.each_with_index do |cat ,x| %>
      <tr>
        <td><%= x+1 %></td>
        <td><%= cat.name %></td>
        <% if cat.parent_id %>
          <% @cat = Category.find(cat.parent_id) %>
          <td><%= @cat.name %></td>
        <% else %>
          <td><%= "-" %></td>
        <% end %>
        <td>
        <%= link_to "Edit", edit_admin_category_path(cat.id) %>
        <%= link_to "Show", admin_category_path(cat.id), :method => :get %>
        <%= link_to "Delete", admin_category_path(cat.id), :confirm => 'Are you sure?', :method => :delete %>
        </td>
      </tr>
    <% end %>
  </table>

app/views/admin/categories/new.html.erb
<h2>New Category</h2>

  <% if @category.errors.any? %>
      <% for message in @category.errors.full_messages %>
          <li><%= message %></li>
      <% end %>
  <% end %>
  
  <%= form_for [:admin,@category] do |cat| %>
    <table>
      <tr>
        <th>Name</th>
        <td>:<td>
        <td><%= cat.text_field :name %></td>
      </tr>
      <tr>
        <th>Parent Category</th>
        <td>:<td>
        <td><%= cat.select :parent_id, @parent_category, { :prompt => true } %></td>     
      </tr>
      <tr>
        <td><%= cat.submit %></td>
        <td></td>
        <td><%= link_to "back", admin_categories_path %></td>
      </tr>
    </table>
  <% end %>

app/views/admin/categories/show.html.erb
<h3>Detail Category <%= @category.name %></h3>
  <table>
     <tr>
       <th>Name</th>
       <td>:</td>
       <td><%= @category.name %></td>
     </tr>
     <tr>  
       <th>Parent Category</th>
       <td>:</td>
       <td><%= @category.parent_id %></td>
     </tr>
  </table>
  
  <%= link_to "back", admin_categories_path %>