config/routes.rb
Tubes::Application.routes.draw do
  root :to => "home#index"
  
  resources :users
  resources :sessions
  resources :categories
  resources :products
  resources :articles
  resources :comments
  
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"  
  
  namespace :admin do
   resources :categories
  end
 

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :id, :title, :body, :user_id
  has_many :comments, :dependent => :destroy
  
    validates :title, :presence => true,
                      :length => {:minimum => 3},
                      :uniqueness => true
    
    validates :body, :presence => true
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :product
  
  attr_accessible :id, :name, :parent_id
  
  validates :name, :presence => true,
                   :length => {:minimum => 3},
                   :uniqueness => true
  
  scope :categorychild, lambda { |parent_id| where("parent_id = ?", parent_id) }
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :id, :name, :description, :price, :weight, :user_id, :category_id
  belongs_to :user
  has_one :category
  
  validates :name, :presence => true,
      	           :length => {:minimum => 3, :maximum => 20}
  
  validates :description, :presence => true,
                          :length => {:minimum =>6}
  
  validates :category_id, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :id, :name, :email, :address, :password, :password_confirmation, :gender , :birthday, :phone_number, :facebook, :blog
  attr_accessor :password
  has_many :products
  before_save :encrypt_password

  validates :name, :presence => true,
      	           :length => {:minimum => 3, :maximum => 20}

  validates :email, :presence => true,
	                  :uniqueness => true,
	                  :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}

  validates :password, :presence => {:on => :create},
                       :confirmation => true
  
  validates :phone_number, :uniqueness => true
  
  validates :gender, :presence => true                  
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def is_admin?
    if self.email == "ian_bowo44@yahoo.com"
      return true
    else
      return false
    end  
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :require_login, :only => [:create, :new, :edit, :update, :destroy]
  before_filter :find_article, :only => [:edit, :update, :show, :destroy]
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.create(params[:article])
    if @article.save
      flash[:notice] = "Success save into database"
      redirect_to articles_path
        else
          flash[:notice] = "Failed save into database"
          render :action => :new
        end
  end
  
  def edit
  end
  
  def update
    if @article.update_attributes(params[:article])
      flash[:notice] = "Success update and save into database"
      redirect_to articles_path
        else
          flash[:notice] = "failed to update and save into database"
          render :action => edit
        end
  end

  def index
    @articles = Article.all
  end

  def show
    @user = User.find(@article.user_id)
    @comment = Comment.new
    @comments = Comment.where("article_id = #{params[:id]}")
  end
  
  def destroy
    @article.destroy
    flash[:notice] = "Success delete from database"
    redirect_to articles_path
  end
  
  def find_article
    @article = Article.find(params[:id])
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    @categories = Category.all
  end
  
  def new
  end

  def create
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
  end
   
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    #@article = Article.find(params[:article_id])
    @comment = Comment.new(params[:comment])
    @user = User.find(@comment.user_id)
    #redirect_to article_path(@article)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to(article_path(params[:comment][:article_id]), :notice => 'Comment was successfully created.') }
        format.js
      end
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @articles = Article.all
    @products = Product.all
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :require_login, :only => [:create, :new, :edit, :update, :destroy]
  before_filter :find_product, :only => [:edit, :update, :destroy, :show]
  before_filter :find_category, :only => [:new, :create, :edit, :update]
  
  def show
    @user = User.find(@product.user_id)
  end
  
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = Product.create(params[:product])
    if @product.save
      flash[:notice] = "success save into database"
      redirect_to :root
    else
      flash[:error] = "Please try again"
      render :action => :new
    end
  end
    
  def edit
  end
  
  def update
    if @product.update_attributes(params[:product])
      flash[:notice] = "Success for update and save into database"
      redirect_to products_path
      else
        flash[:error] = "failed for update"
        render :action => :edit
      end
  end
  
  def destroy
    @product.destroy
    flash[:notice] = "success for delete"
    redirect_to products_path
  end
  
  def find_product
    @product = Product.find(params[:id]) 
  end
  
  def find_category
    @parent_category = Category.where("parent_id IS not null").map{|c| [c.name, c.id]}
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
  
  def create
   user = User.authenticate(params[:email], params[:password])
   if user
     session[:user_id] = user.id
     if current_user.is_admin?
       redirect_to admin_categories_path
     else
       redirect_to user_path(user.id), :method => :get 
     end
    else
      flash[:error] ="Invalid email or password"
      redirect_to :root
    end
  end

  def destroy
   session[:user_id] = nil
   redirect_to :root
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :find_user, :only => [:show, :edit, :update]
  
  def index
  end

  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(params[:user])
      if verify_recaptcha
        if @user.save
          UserMailer.registration_confirmation(@user).deliver
          flash[:notice] = "Success save into database"
          redirect_to user_path(@user.id), :method => :get
        else
          flash[:error] = "faild save into database"
          render :action => :new
        end
      else
      flash[:error] = "There was an error with the recaptcha code below.
                     #Please re-enter the code and click submit."
      render :action => :new
      end
  end

  # PUT /users/1
  def update
      if @user.update_attributes(params[:user])
        flash[:notice] = "Success update and save into database"
        redirect_to user_path(@user.id), :method => :get
      else
        flash[:error] = "Failed update"
        render :action => :edit
      end
  end

  def destroy
  end
  
  def find_user
    @user = User.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def welcome_text
    str = "" #jika user telah login, tampilkan welcome textnya 
    if current_user 
      str = "Welcome, #{current_user.email}"
    else 
      str += link_to "Signup", sign_up_path 
    end 
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tubes</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="wrapper">
    <header class="first_head">
      <h1>Welcome to my Store</h1>
    </header>
    <hr />
    
    <nav class="menu">
      <ul>
        <li><%= link_to 'Home', :root %></li>
        <li><%= link_to 'Products', products_path %></li>
        <li><%= link_to 'Articles', articles_path %></li>
        <% if session[:user_id]%>
          <li><%= link_to 'Category', categories_path %></li>
          <% if current_user.is_admin? %>
           <li><%= link_to 'Category', admin_categories_path %></li>
          <% end %>
        <% else %>
          <li><%= link_to 'Category', categories_path %></li>
        <% end %>        
      </ul>
      <br />
      <div class="clear"></div>
    </nav>
    <hr />
    
    <section>
      <p class="sign_up"><%= raw(welcome_text) %></p>
      <div class="clear"></div>
    </section>
    
    <aside id="sidecontent">
    <% if current_user %>
       <ul class="sideafterlogin">
         <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
         <li><%= link_to "Sell a Product", new_product_path %></li>
         <li><%= link_to "Share an Article", new_article_path %></li>
         <li><%= link_to "Logout", log_out_path %></li>
       </ul>
       <hr />
      <%= render :partial => "shared/list_categories" %>
      <% else %>
        <%= render "sessions/log_in" %>
      <% end %>
    </aside>
    
    <section id="content">
      <div id="notice" >
        <% if flash[:notice] %>
          <%= flash[:notice] %>
        <% end %>
        <% if flash[:error] %>
          <%= flash[:error] %>
        <% end %>
      </div>
      <%= yield %>
    </section>
    <div class="clear"></div>
    
    <hr />
    <footer>
	    <p>Copyright &#169; Ardhi Sofyan W 2012</p>
    </footer>
    </div>
  </body>
</html>

app/views/shared/_list_categories.html.erb
<h2>List Category</h2>
  <ul class="sidelistcategory">
    <% Category.all.each do |category| %>
      <% if category.parent_id %>
        <li class="tab"><%= category.name %></li>
      <% else %>
        <li><%= category.name %></li>
      <% end %>
    <% end %>
  </ul>